language: node_js
before_install: cd webapp
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git: 
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: webapp/dist/
  target_branch: gh-pages
  commit_message: "Deplay Release"
  on:
    branch: angular