version: '3.8'
services:
  server:
    container_name: '${PROJECT_NAME}-server'
    image: 'meeli/server'
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: '${JWT_SECRET}'
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - '${SERVER_PORT}:8000'
    networks:
      - default
  webapp:
    container_name: '${PROJECT_NAME}-web'
    image: 'meeli/web'
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      SERVER_BASE_URL: '${SERVER_BASE_URL}'
    ports:
      - '${WEBAPP_PORT}:80'
    networks:
      - default
networks:
  default:
    driver: bridge
