version: '3.8'
services:
  redis:
    container_name: '${PROJECT_NAME}-redis'
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - default
  server:
    container_name: '${PROJECT_NAME}-server'
    image: 'meeli/server'
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on: 
      - redis
    environment:
      SERVER_JWT_SECRET: ${SERVER_JWT_SECRET}
      SERVER_DB_HOST: ${SERVER_DB_HOST}
      SERVER_DB_NAME: ${SERVER_DB_NAME}
      SERVER_DB_USER: ${SERVER_DB_USER}
      SERVER_DB_PASSWORD: ${SERVER_DB_PASSWORD}
      SERVER_DB_PORT: ${SERVER_DB_PORT}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_REDIS_HOST: ${SERVER_REDIS_HOST}
      SERVER_REDIS_PORT: ${SERVER_REDIS_PORT}
      SERVER_REDIS_PASSWORD: ${SERVER_REDIS_PASSWORD}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    networks:
      - default
  webapp:
    container_name: '${PROJECT_NAME}-web'
    image: 'meeli/web'
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      WEBAPP_SERVER_BASE_URL: '${WEBAPP_SERVER_BASE_URL}'
    ports:
      - '${WEBAPP_PORT}:80'
    networks:
      - default
networks:
  default:
    driver: bridge
