version: '3.8'
services:
  postgis:
    container_name: '${PROJECT_NAME}-postgis'
    image: postgis/postgis:12-master
    restart: always
    environment:
      POSTGRES_DB: ${SERVER_DB_NAME}
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD}
    ports:
      - '${SERVER_DB_PORT}:5432'
    networks:
      - default
    volumes:
      - ./db/cr-administrative-division.sql:/docker-entrypoint-initdb.d/cr-administrative-division.sql
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
  redis:
    container_name: '${PROJECT_NAME}-redis'
    image: 'redis:alpine'
    restart: on-failure
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - default
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  server:
    container_name: '${PROJECT_NAME}-server'
    image: 'meeli/server'
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgis
      - redis
    environment:
      SERVER_JWT_SECRET: ${SERVER_JWT_SECRET}
      SERVER_DB_HOST: ${SERVER_DB_HOST}
      SERVER_DB_NAME: ${SERVER_DB_NAME}
      SERVER_DB_USER: ${SERVER_DB_USER}
      SERVER_DB_PASSWORD: ${SERVER_DB_PASSWORD}
      SERVER_DB_PORT: ${SERVER_DB_PORT}
      SERVER_HTTP_PORT: ${SERVER_HTTP_PORT}
      SERVER_HTTPS_PORT: ${SERVER_HTTPS_PORT}
      SERVER_REDIS_HOST: ${SERVER_REDIS_HOST}
      SERVER_REDIS_PORT: ${SERVER_REDIS_PORT}
      SERVER_REDIS_PASSWORD: ${SERVER_REDIS_PASSWORD}
      SERVER_SESSION_TIMEOUT: ${SERVER_SESSION_TIMEOUT}
    ports:
      - '${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}'
      - '${SERVER_HTTPS_PORT}:${SERVER_HTTPS_PORT}'
    networks:
      - default
  webapp:
    container_name: '${PROJECT_NAME}-web'
    image: 'meeli/web'
    restart: unless-stopped
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      WEBAPP_SERVER_BASE_URL: '${WEBAPP_SERVER_BASE_URL}'
    ports:
      - '${WEBAPP_PORT}:80'
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  postgis_data:
